# This file configures the controllers we use on the robot
engrais:
    # Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50  

    # Velocity Controllers for the wheels ------------------------
    leftWheel_controller:
        type: effort_controllers/JointVelocityController
        joint: left_wheel_joint
        pid: {p: 10.0, i: 0.2, d: 0.0, i_clamp: 0.0}
    rightWheel_controller:
        type: effort_controllers/JointVelocityController
        joint: right_wheel_joint
        pid: {p: 10.0, i: 0.2, d: 0.0, i_clamp: 0.0}
