<?xml version="1.0" ?>
<sdf version="1.5" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- macro to compute the inertia of the cylinder -->
    <xacro:macro name="cylinder_inertia" params="m r h">
        <inertia>
            <ixx>${m*(3*r*r+h*h)/12}</ixx> <ixy>0</ixy> <ixz>0</ixz>
            <iyy>${m*(3*r*r+h*h)/12}</iyy> <iyz>0</iyz>
            <izz>${m*r*r/2}</izz>
        </inertia>
    </xacro:macro>

    <!-- constants -->
    <!-- the body constants (body = base = a kind of root), use to make the plant more stabled -->
    <xacro:property name="body_mass"   value="0.100" /> <!-- mass of the body - kg -->
    <xacro:property name="body_radius" value="0.100" /> <!-- radius of the body - m -->
    <xacro:property name="body_length" value="0.010" /> <!-- length of the body - m -->
    <!-- the stem constant -->
    <xacro:property name="stem_mass"   value="0.010" /> <!-- mass of the stem - kg -->
    <xacro:property name="stem_radius" value="0.050" /> <!-- radius of the stem - m -->
    <xacro:property name="stem_length" value="1.000" /> <!-- length of the stem - m -->

    <model name="plantgreen">
        <!-- the body of the plant -->
        <link name="body">
            <pose>0 0 ${body_length/2} 0 0 0</pose>
            <inertial>
                <mass> ${body_mass} </mass>
                <cylinder_inertia  m="${body_mass}" r="${body_radius}" h="${body_length}" />
            </inertial>
            <collision name="collision">
                <geometry>
                    <cylinder>
                        <length>${body_length}</length>
                        <radius>${body_radius}</radius>
                    </cylinder>
                </geometry>
            </collision>
            <visual name="visual">
                <geometry>
                    <cylinder>
                        <length>${body_length}</length>
                        <radius>${body_radius}</radius>
                    </cylinder>
                </geometry>
                <!-- we want the green plant to be green... -->
                <material>
                    <ambient>0.1 0.5 0.1 1</ambient>
                    <diffuse>0.1 0.5 0.2 1</diffuse>
                    <specular>0 0.5 0 0</specular>
                    <emissive>0 0 0 1</emissive>
                </material>
            </visual>
        </link>

        <!-- the stem of the plant -->
        <link name="stem">
            <pose>0 0 ${body_length+stem_length/2+0.001} 0 0 0</pose>
            <inertial>
                <mass> ${stem_mass} </mass>
                <cylinder_inertia  m="${stem_mass}" r="${stem_radius}" h="${stem_length}" />
            </inertial>
            <collision name="collision">
                <geometry>
                    <cylinder>
                        <length>${stem_length}</length>
                        <radius>${stem_radius}</radius>
                    </cylinder>
                </geometry>
            </collision>
            <visual name="visual">
                <geometry>
                    <cylinder>
                        <length>${stem_length}</length>
                        <radius>${stem_radius}</radius>
                    </cylinder>
                </geometry>
                <material>
                    <ambient>0.1 1 0.1 1</ambient>
                    <diffuse>0.1 1 0.1 1</diffuse>
                    <specular>0 1 0 0</specular>
                    <emissive>0 0 0 1</emissive>
                </material>
            </visual>
        </link>

       <!-- fixed joint between the stem and the body, as it is not possible to define a fixed joint, we define a revolute joint with no limits -->
       <joint name="body_stem_joint" type="revolute">
          <parent>body</parent>
          <child>stem</child>
          <axis>
            <xyz>0 0 1</xyz>
            <limit>
              <upper>0</upper>
              <lower>0</lower>
            </limit>
          </axis>
        </joint>

    </model>
</sdf>
